### ISSUE TITLE
source 

### ISSUE THREAD

**Issue by savioruz** [lutfailham96/libernet-proprietary#3]
ada source code v2ray.ipk ?
oiya corkscrew ane make dari raspberry repo bisa kan?

**Comment by lutfailham96** [comment]
> ada source code v2ray.ipk ?
> oiya corkscrew ane make dari raspberry repo bisa kan?

semua source code ada di repository author masing-masing
bisa tidaknya tergantung kernel & architecture yang dipakai

**Comment by savioruz** [comment]
v2ray.ipk bagi source mau build

**Comment by lutfailham96** [comment]
> v2ray.ipk bagi source mau build

saya kira sudah selesai kasusnya, bisa saya close
